#!/usr/bin/env zsh
#
# setup_starship_prompt: Use starship with the built-in Zsh prompt system conventions.
#

#function prompt_starship_setup {

(( $+commands[starship] )) || {
  print -ru2 -- "prompt_starship_setup: starship command not found"
  return 1
}

# When loaded through the prompt command, these prompt_* options will be enabled
prompt_opts=(cr percent sp subst)

# Set the starship config based on an argument if one is provided.
# (N-.) => null glob, follow symlinks, match files
if [[ -n "$1" ]]; then
  local -a configs=(
    "$1"(N-.)
    "${ZDOTDIR:-${XDG_CONFIG_HOME:-$HOME/.config}/zsh}/themes/${1}.toml"(N-.)
    "${XDG_CONFIG_HOME:-$HOME/.config}/starship/${1}.toml"(N-.)
  )
  (( $#configs )) && export STARSHIP_CONFIG=$configs[1]
fi

# Initialize starship.
source <(starship init zsh)

#}
